_wandb:
    value:
        cli_version: 0.23.1
        e:
            u1dl5vwwj4qho7iz8kpywy4u9010j3me:
                args:
                    - --env_name
                    - Go1Handstand
                    - --use_wandb=True
                    - --num_evals=1000
                    - --num_timesteps=10000000
                codePath: learning/train_jax_ppo.py
                codePathLocal: learning/train_jax_ppo.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "877105795072"
                        used: "286957375488"
                email: yw6514@nyu.edu
                executable: /home/epon/anaconda3/envs/Doggy/bin/python
                git:
                    commit: 2881d8a40985ed1bd56a52326f8a95572fbd2d0f
                    remote: git@github.com:Epon-Wang/mujoco_playground.git
                gpu: NVIDIA GeForce RTX 5080 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 7680
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5080 Laptop GPU
                      uuid: GPU-98dfd104-0ca0-8e79-cfce-5de4d1ccc3ce
                host: StrangeLab
                memory:
                    total: "66846187520"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.35
                program: /home/epon/mujoco_playground/learning/train_jax_ppo.py
                python: CPython 3.11.14
                root: /home/epon/mujoco_playground
                startedAt: "2025-12-04T05:28:52.943399Z"
                writerId: u1dl5vwwj4qho7iz8kpywy4u9010j3me
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 12
                - 45
                - 105
            "2":
                - 1
                - 12
                - 45
                - 105
            "3":
                - 13
                - 61
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
Kd:
    value: 0.5
Kp:
    value: 35
action_repeat:
    value: 1
action_scale:
    value: 0.3
ctrl_dt:
    value: 0.02
energy_termination_threshold:
    value: .inf
env_name:
    value: Go1Handstand
episode_length:
    value: 500
impl:
    value: jax
init_from_crouch:
    value: 0
nconmax:
    value: 245760
njmax:
    value: 200
noise_config:
    value:
        level: 1
        scales:
            gravity: 0
            gyro: 0.2
            joint_pos: 0.01
            joint_vel: 1.5
            linvel: 0
reward_config:
    value:
        scales:
            action_rate: 0
            dof_acc: 0
            dof_pos_limits: -1
            energy: 0
            orientation: 2
            pose: 0.001
            stay_still: -0.01
            termination: -1
            torques: 0
sim_dt:
    value: 0.004
soft_joint_pos_limit_factor:
    value: 0.9
